language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tkim0719/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true tkim0719/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-726150366068"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
