language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tkim0719/docker-react -f Dockergile.dev .
script:
  - docker run -e CI=true tkim0719/docker-react npm run test
